Algoritmo "Antecessor do valor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : lê um valor e informa o seu antecessor
// Autor(a)    : Nicolau Sara
// Data atual  : 11/02/2023
Var
// Seção de Declarações das variáveis 
valor,antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor:")
leia(valor)

antecessor:=(valor-1)entao
escreval("O antecessor deste número é:",antecessor)



Fimalgoritmo