Algoritmo "se maior de idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Lê a idade do usuario e informa se é maior ou menor de idade
// Autor(a)    : Nicolau Sara
// Data atual  : 14/01/2023
Var
// Seção de Declarações das variáveis 
idade:inteiro

Inicio
escreval("Quantos anos voçê tem?")
leia(idade)

se idade>=18 entao
escreval("Maior de Idade")
senao
escreval("Menor de idade")

fimse
Fimalgoritmo
